### ISSUE TITLE
[1.16] Config Missing

### ISSUE THREAD

**Issue by NillerMedDild** [SlimeKnights/TinkersMechworks#106]
Hi o/ Thanks for porting to 1.16!

The config is missing, so I can't stop spawning of Copper/Aluminum, would you mind re-adding that? :)

**Comment by fuj1n** [comment]
The config file moved and is no longer in it's own folder, does the file not appear in `config/tmechworks-common.toml`?

**Comment by NillerMedDild** [comment]
My bad, I see it now, thanks :)
