### ISSUE TITLE
Issue with drawbridges and ftbteams/ftbchunks.

### ISSUE THREAD

**Issue by Micaxs** [SlimeKnights/TinkersMechworks#108]
There is an issue with FTBTeams / FTBChunks and Drawbridges. These do not work in claimed chunks, occurs in All the mods 6 modpack version 1.3.3 on minecraft version 1.16.4.

Works fine outside of a claimed area, doesn't work inside a claimed area.

**Comment by fuj1n** [comment]
You need to give MechworksWorker access to your chunks.

**Comment by Micaxs** [comment]
> You need to give MechworksWorker access to your chunks.

Already did this, issue is still there.

**Comment by fuj1n** [comment]
The issue seems to be with FTBChunks itself, https://github.com/FTBTeam/FTB-Chunks/issues/58 https://github.com/FTBTeam/FTB-Chunks/issues/59 (in 59, check comment)

Closing this for now, will reopen if it becomes apparent that it is a Mechworks issue.

**Comment by fuj1n** [comment]
Update: should be fixed as of FTB Chunks 2.1.50
