### ISSUE TITLE
Server crash after update to forge 35.1.37

### ISSUE THREAD

**Issue by Seniorendi** [SlimeKnights/TinkersMechworks#109]
Hey, 
when i want to start my server, it crashes. I have a world with some placed drawbridges. 

Log: https://gist.github.com/Seniorendi/b4e87ec5db7494197b18cd2331d14530

Version: 1.16.3+-2.2.2
Forge version: 35.1.37
Mantle version: 1.6.74

**Comment by Seniorendi** [comment]
Removing TMechwors fixes the issue.

**Comment by KnightMiner** [comment]
This is actually a Mantle problem, looks like I accidently removed a field that Mechworks used. If you can, downgrade Mantle and this will be fixed. Otherwise I'll release a new Mantle build with the fix in the next couple of days.

**Comment by Seniorendi** [comment]
Thank you!

**Comment by fuj1n** [comment]
Should also be fixed on my end as of Tinkers' Mechworks v2.2.3
