### ISSUE TITLE
Tinkers' Mechworks (tmechworks) has failed to load correctly

### ISSUE THREAD

**Issue by JustToast21** [SlimeKnights/TinkersMechworks#110]
Hey i have a problem while try to load the All the Mods 6 Modpack on forge i get this Crashcode

![Screenshot 2022-05-05 164238](https://user-images.githubusercontent.com/104998228/166948931-450707e6-0b44-412d-85c7-b4d7364f266c.png)

![hhhh](https://user-images.githubusercontent.com/104998228/166949258-d8adc0f7-1406-4f4f-a164-c70ae44846d7.png)

**Comment by JustToast21** [comment]
![hhhh](https://user-images.githubusercontent.com/104998228/166949197-0393559f-d410-4b78-9453-9bde4ee69c42.png)

**Comment by fuj1n** [comment]
From a quick look at the logs, looks more like an issue with RandomPatches failing to patch some code, not sure why Tinkers' Mechworks was credited with that crash.
