### ISSUE TITLE
Blacklist for drawbridges doesn't work

### ISSUE THREAD

**Issue by jordsta95** [SlimeKnights/TinkersMechworks#78]
Hey there, so after adding <ThermalExpansion:Strongbox:1> to the blacklist for the drawbridges it is impossible to place them into the drawbridge, however it is still possible to shift-click it in.Is there any way to prevent this, or is it something on the mod's end?

**Comment by Glassmaker** [comment]
ThermalExpansion:Strongbox:1 wouldn't work at all, you need to put it as ThermalExpansion:Strongbox

I checked shift clicking, it's working fine over here, the item doesn't get in.

**Comment by Glassmaker** [comment]
Reopened the issue as the issue was discovered after removing COFHCore
