### ISSUE TITLE
[Suggestion] Change drawbridge directionality settings.

### ISSUE THREAD

**Issue by lyqyd** [SlimeKnights/TinkersMechworks#79]
The drawbridge block placement directionality is a little strange to try to use to get specific block placements.  For instance, using a drawbridge in any orientation with the "neutral" direction picked will always place a block with the fakeplayer's pitch and yaw both set to zero (placement level, south).  Using any other orientation setting with a vertically extending drawbridge will always set the pitch to -90 or 90, and will use a NSEW (depending on setting) yaw value.  Using a horizontally extending piston, the neutral setting is (of course) still placing things at 0 pitch and 0 yaw.  Using the up or down orientations will place things up and forward or down and back, while the sideways orientations are the only way to achieve 0-pitch non-south orientations.

I propose a change to the GUI to separate the pitch and yaw settings.  This would keep the four directional arrows, but get rid of the neutral setting in between them, then add a up/neutral/down setting next to it. The four existing arrows would be re-purposed for yaw, the four cardinal directions, while the pitch settings could be used in conjunction to allow non-south neutral pitch in vertically oriented drawbridges, for instance.  This would allow finer control of block placement, especially for blocks which can be placed in many different orientations.

I would be happy to contribute code toward this if this suggestion is aligned with the direction the mod is going in, but I don't have much experience with GUI stuff in Minecraft.

**Comment by fuj1n** [comment]
Done
