### ISSUE TITLE
Fake Playername for drawbridges?

### ISSUE THREAD

**Issue by Jacob345k** [SlimeKnights/TinkersMechworks#90]
I want to be able to use drawbridges in my griefprevention claim, to do this i need to /trust the playername of the person placing the blocks, what's the fake playername for drawbridges?

**Comment by KnightMiner** [comment]
Out don't need a fake player to place blocks. The drawbridge likely places it using the world and no player

**Comment by Jacob345k** [comment]
Drawbridges placed by the player cannot build in said player's claim using the plugin Griefprevention, is there a way around this?

**Comment by fuj1n** [comment]
It appears that the fake player name is Player.Drawbridge
