### ISSUE TITLE
Crash when clicking on Tinkers' Mechworks in the mod list.

### ISSUE THREAD

**Issue by Lurmey** [SlimeKnights/TinkersMechworks#98]
As the title says. Complete crash to desktop when clicking on Tinkers' Mechworks in the Forge mod list, in an attempt to edit the config from within the game.
Crash report: 
[crash-2019-10-29_18.17.01-client.txt](https://github.com/SlimeKnights/TinkersMechworks/files/3785152/crash-2019-10-29_18.17.01-client.txt)

**Comment by fuj1n** [comment]
I'll look into that, but an FYI, Forge doesn't currently support in-game configs
